# Generated by Django 4.2.10 on 2024-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_field_2_post_field_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='field_2',
            field=models.IntegerField(default=42),
        ),
    ]
